on: 
   issue_comment :
     types: [created, edited, deleted]
#    pull_request :
#      branches:
#      - master

jobs:
    stale:
     runs-on: ubuntu-latest
     permissions:
      issues: write
      pull-requests: write
     steps:
      - uses: alexjurkiewicz/pr-comment-github-deployment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - run : |
             npm i -g vercel
             npm install -g npm@8.3.0
             npm install vercel


