name: pull request comment
on:
  issue_comment:                                     
    types: [created, edited, deleted]

jobs:
 job01:
   if: contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, 'this is deployment link')   # check if the comments come from pull request, exclude those from issue.
   runs-on: [ubuntu-latest]
   steps:
     - uses: github-actions-up-and-running/pr-comment@v1.0.1
       with:
           repo-token: ${{ secrets.GITHUB_TOKEN }}
           message: 1Nice PR!👍
     - name: say hello
       if: contains(github.event.comment.body, 'get vercel preview')   # check the comment if it contains the keywords "get vercel preview"
       run: |
         echo say hello
         echo "github.event.comment is: $github.event.comment"
         echo "github.event is: $github.event"
         echo "github.event.comment.html_url is : $github.event.comment.html_url"
         echo "GITHUB_SHA is: $GITHUB_SHA"
#      - uses: github-actions-up-and-running/pr-comment@v1.0.1
#        with:
#            repo-token: ${{ secrets.GITHUB_TOKEN }}
#            message: 1Nice PR!👍
