name: Explorer
on:
  push:
   branches: [master]
   paths:
      - 'explorer/**'
  pull_request:
    branches:
     - master
    types: [opened, synchronize, reopened]
    paths:
      - 'explorer/**'
jobs:
  check-explorer:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: explorer
    if: "!contains(github.event.head_commit.message, '[skip ci]')" 
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: explorer/package-lock.json
      - run: npm i -g npm@7
      - run: npm ci
      - run: npm run format
      - run: npm run build
      - run: npm run test
      - uses: actions/checkout@v2
      - uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }} # Required
          GITHUB_TOKEN: ${{ secrets.PAT }} #Optional 
          VERCEL_ORG_ID: ${{ secrets.ORG_ID}}  #Required
          VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID}} #Required 
          working-directory: ./explorer
#           scope: "avnshrai"  
