name : explorer_preview
on:
  workflow_run:
    workflows: ["Explorer_build&test_on_PR"]
    types: 
      - completed
#   pull_request:
#     branches:
#      - master
#     paths:
#       - 'explorer/**'
jobs:
   explorer_preview:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
           ref: Avnshrai:patch-55
#           ref: ${{ github.event.pull_request.head.sha }}
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          working-directory: ./explorer
          scope: ${{ secrets.TEAM_ID }}
#       - name: Waiting for 200 from the Vercel Preview
#         uses: patrickedqvist/wait-for-vercel-preview@v1.1.1
# #         id: waitFor200
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           max_timeout: 60
#   # access preview url
#       - run: echo ${{steps.waitFor200.outputs.url}}
