name: Close Pull Request

# only trigger on pull request closed events
on:
  pull_request_target:
    branches:
     - master
    paths:
      - 'explorer/**'
    types: [ closed ]

jobs:
  production:
   needs: check-explorer
   runs-on: ubuntu-latest
   if: github.event.pull_request.merged == true
   steps:
     - uses: actions/checkout@v2
     - uses: amondnet/vercel-action@v20
       with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.PAT }} #Optional 
          vercel-args: '--prod' #for production
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
          working-directory: ./explorer
          scope: ${{ secrets.TEAM_ID }}
