name : solana_main
on:
  push:
    branches:  [master]
    tags : /^v\d+\.\d+/
  pull_request:
    branches:  [master]
    tags : /^v\d+\.\d+/
jobs:
  check-explorer:
    runs-on: ubuntu-latest
    steps:
      - name: release artifact 
        run: |
            choco install llvm --force -y
            choco install openssl cmake make -y
            refreshenv

