name : solana_main
on:
  push:
    branches:  [master]
    tags : /^v\d+\.\d+/
  pull_request:
    branches:  [master]
    tags : /^v\d+\.\d+/
jobs:
  check-explorer:
    runs-on: windows-latest
    steps:
      - run: echo "this job will solve PR problem"
